// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringSQLServer.Infrastructure;

namespace MonitoringSQLServer.Infrastructure.Migrations.SqlServerMigrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201117193939_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MonitoringSQLServer.Domain.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MonitoringSQLServer.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MonitoringSQLServer.Domain.RoleGroup", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("RoleGroup");
                });

            modelBuilder.Entity("MonitoringSQLServer.Domain.Statistics", b =>
                {
                    b.Property<short>("blocking_session_id")
                        .HasColumnType("smallint");

                    b.Property<string>("client_interface_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("database_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("host_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_wait_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("query_plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("reads")
                        .HasColumnType("bigint");

                    b.Property<short>("session_id")
                        .HasColumnType("smallint");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("wait_resource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("wait_time")
                        .HasColumnType("int");

                    b.Property<string>("wait_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("writes")
                        .HasColumnType("bigint");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("MonitoringSQLServer.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MonitoringSQLServer.Domain.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("MonitoringSQLServer.Domain.RoleGroup", b =>
                {
                    b.HasOne("MonitoringSQLServer.Domain.Group", "Group")
                        .WithMany("RoleGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringSQLServer.Domain.Role", "Role")
                        .WithMany("RoleGroups")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitoringSQLServer.Domain.UserGroup", b =>
                {
                    b.HasOne("MonitoringSQLServer.Domain.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoringSQLServer.Domain.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
